name: AevyCore
version: '${project.version}'
main: fun.aevy.aevycore.AevyCore
authors: [ Sorridi, Niketion ]
description: Core API plugin
website: https://sorridi.xyz/plugins/aevycore
depend: [ ActionBarAPI ]
load: STARTUP
commands:
  aevy:
    description: Main command of the core.
